# alternative env var GARDEN_KUBECONFIG
# used to create kcp secret kcp-system/gardener-credentials
gardenKubeconfig: /path/to/garden/kubeconfig

# if ommitted, defaults to kcp-system
kcpNamespace: kcp-system
# if ommitted, defaults to garden
gardenNamespace: garden
# if ommitted, defaults to skr
skrNamespace: skr

subscriptions:
    # name is SecretBinding name in garden
  - name: subscription-1
    provider: aws
    isDefault: true

# gardener or kyma (once implemented
networkOwner: gardener

# shoot oidc client id
oidcClientId: abc-123
# shoot oidc issuer url
oidcIssuerUrl: https://oidc.example.com

# shoot admins
administrators:
  - john.smith@example.com

cloudProfiles:
  aws: aws
  azure: az
  gcp: gcp
  openstack: converged-cloud-kyma

# if false then the secret gardener-credentials must not exist in KCP
# if true then the secret gardener-credentials will be overwritten in case it exists
# in CI unit/controller tests when testinfra/controller-runtime/testenv is used it should be false
# in local dev writing/debugging e2e test using local kind it can be true to avoid manual secret deletion before each run
overwriteGardenerCredentials: false
