resources:
- configmap.yaml
- manager.yaml
- secret-aws.yaml
- secret-gcp.yaml

configMapGenerator:
- behavior: merge
  literals:
  - GARDENER_NAMESPACE=garden-spm-test01
  - SKR_PROVIDERS=/var/kyma/cloud-manager/skr/providers/
  - GCP_CLIENT_RENEW_DURATION=5m
  - GCP_RETRY_WAIT_DURATION=5s
  - GCP_OPERATION_WAIT_DURATION=5s
  - NFS_BACKUP_SCHEDULER_DEADLINE=30s
  name: manager-env

secretGenerator:
- behavior: merge
  literals:
  - AWS_ROLE_NAME=CrossAccountPowerUser
  - AWS_ACCESS_KEY_ID=xxx
  - AWS_SECRET_ACCESS_KEY=xxx
  name: manager-env-aws
- behavior: merge
  literals:
  - credentials.json=xxx
  name: manager-env-gcp
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: controller
  newTag: latest
