# This rule is not used by the project cloud-manager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over cloud-control.kyma-project.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloud-manager
    app.kubernetes.io/managed-by: kustomize
  name: cloud-control-vpcnetwork-admin-role
rules:
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - vpcnetworks
  verbs:
  - '*'
- apiGroups:
  - cloud-control.kyma-project.io
  resources:
  - vpcnetworks/status
  verbs:
  - get
