apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: AzureVpcPeering
metadata:
  labels:
    app.kubernetes.io/name: azurevpcpeering
    app.kubernetes.io/instance: azurevpcpeering-sample
    app.kubernetes.io/part-of: cloud-resources-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-resources-manager
  name: azurevpcpeering-sample
spec:
  # TODO(user): Add fields here
