apiVersion: v1
data:
  details: |-
    body:
      - name: configuration
        widget: Panel
        source: spec
        children:
          - name: spec.memorySizeGb
            source: memorySizeGb
            widget: Labels
          - name: spec.redisVersion
            source: redisVersion
            widget: Labels
          - name: spec.tier
            source: tier
            widget: Labels
          - name: spec.authEnabled
            source: authEnabled
            widget: Labels


      - name: spec.redisConfigs
        widget: Panel
        source: spec
        children:
          - source: redisConfigs
            widget: Labels

      - name: spec.ipRange
        widget: Panel
        source: spec
        children:
          - name: spec.ipRange.name
            source: ipRange.name
            widget: Labels

      - name: spec.authSecret
        widget: Panel
        source: spec
        children:
          - source: authSecret.name
            name: spec.authSecret.name
            widget: Labels
          - source: authSecret.labels
            name: spec.authSecret.labels
            widget: Labels
          - source: authSecret.annotations
            name: spec.authSecret.annotations
            widget: Labels


      - name: spec.maintenancePolicy
        widget: Panel
        source: spec
        children:
          - source: maintenancePolicy.dayOfWeek.day
            name: spec.maintenancePolicy.dayOfWeek.day
            widget: Labels
          - source: maintenancePolicy.dayOfWeek.startTime
            name: spec.maintenancePolicy.dayOfWeek.startTime
            widget: Labels


      - name: status
        widget: Panel
        source: status
        children:
          - widget: Labels
            source: state
            name: status.state
  form: |
    - path: spec.memorySizeGb
      name: spec.memorySizeGb
      required: true
    - path: spec.redisVersion
      name: spec.redisVersion
      required: true
      disableOnEdit: true
    - path: spec.tier
      name: spec.tier
      required: true
      disableOnEdit: true

    - path: spec.authEnabled
      name: spec.authEnabled
      required: false
    - path: spec.ipRange.name
      name: spec.ipRange.name
      required: false

    - path: spec.redisConfigs
      name: spec.redisConfigs
      required: false
      widget: KeyValuePair

    - path: spec.authSecret
      name: spec.authSecret
      widget: FormGroup
      required: false
      children:
        - path: name
          name: spec.authSecret.name
          widget: Text
          required: true
          disableOnEdit: true
        - path: labels
          name: spec.authSecret.labels
          required: false
          widget: KeyValuePair
          disableOnEdit: true
        - path: annotations
          name: spec.authSecret.annotations
          required: false
          widget: KeyValuePair
          disableOnEdit: true

    - path: spec.maintenancePolicy
      name: spec.maintenancePolicy
      required: false
      widget: FormGroup
      children:
        - path: dayOfWeek.day
          name: spec.maintenancePolicy.dayOfWeek.day
          required: true
        - path: dayOfWeek.startTime.hours
          name: spec.maintenancePolicy.dayOfWeek.startTime.hours
          required: true
        - path: dayOfWeek.startTime.minutes
          name: spec.maintenancePolicy.dayOfWeek.startTime.minutes
          required: true
  general: |
    resource:
        kind: GcpRedisInstance
        group: cloud-resources.kyma-project.io
        version: v1beta1
    urlPath: gcpredisinstances
    name: GCP Redis Instances
    scope: namespace
    category: Storage
    icon: shelf
    description: >-
        GcpRedisInstance description here
  list: |-
    - source: status.state
      name: status.state
      sort: true
  translations: |
    en:
      configuration: Configuration
      status: Status
      status.state: State
      spec.memorySizeGb: Memory Size (Gb)
      spec.redisVersion: Redis Version
      spec.tier: Tier
      spec.authEnabled: Auth Enabled
      spec.ipRange: Ip Range
      spec.ipRange.name: Ip Range Name
      spec.transitEncryptionMode: Transit Encryption Mode
      spec.authSecret: Authentication Secret
      spec.authSecret.name: Name
      spec.authSecret.labels: Labels
      spec.authSecret.annotations: Annotations
      spec.maintenancePolicy: Maintenance Policy
      spec.maintenancePolicy.dayOfWeek.day: Day
      spec.maintenancePolicy.dayOfWeek.startTime: Start Time
      spec.maintenancePolicy.dayOfWeek.startTime.hours: Hours
      spec.maintenancePolicy.dayOfWeek.startTime.minutes: Minutes
      spec.redisConfigs: Redis Configuration
kind: ConfigMap
metadata:
  annotations:
    cloud-resources.kyma-project.io/version: v0.0.3
  labels:
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    cloud-manager: ui-cm
  name: gcpredisinstances-ui.operator.kyma-project.io
  namespace: kyma-system
