apiVersion: cloud-resources.kyma-project.io/v1beta1
kind: GcpNfsVolumeBackup
metadata:
  labels:
    app.kubernetes.io/name: gcpnfsvolumebackup
    app.kubernetes.io/instance: gcpnfsvolumebackup-sample
    app.kubernetes.io/part-of: cloud-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cloud-manager
  name: gcpnfsvolumebackup-sample
spec:
  source:
    volume:
      name: my-gcp-nfs-volume
      namespace: default
  location: us-west1
  # AccessibleFrom defines who can access this backup for restore.
  # Use type: All to allow access from all shoots in the same global account.
  # Use type: Specific with targets to restrict access to specific shoots.
  accessibleFrom:
    type: All
  # Example with specific targets:
  # accessibleFrom:
  #   type: Specific
  #   targets:
  #     - shoot-prod-1
  #     - shoot-staging-1
