## Append samples of your project ##
resources:
- cloud-control_v1beta1_nfsinstance.yaml
- cloud-control_v1beta1_vpcpeering.yaml
- cloud-control_v1beta1_iprange.yaml
- cloud-control_v1beta1_scope.yaml
- cloud-resources_v1beta1_cloudresources.yaml
- cloud-resources_v1beta1_awsnfsvolume.yaml
- cloud-resources_v1beta1_iprange.yaml
- cloud-resources_v1beta1_gcpnfsvolume.yaml
- cloud-resources_v1beta1_awsnfsvolumebackup.yaml
- cloud-resources_v1beta1_gcpnfsvolumebackup.yaml
- cloud-resources_v1beta1_gcpnfsvolumerestore.yaml
- cloud-resources_v1beta1_azurevpcpeering.yaml
- cloud-resources_v1beta1_nfsbackupschedule.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
