apiVersion: v1
data:
  details: |-
    body:
      - name: configuration
        widget: Panel
        source: spec
        children:
          - name: spec.autoMinorVersionUpgrade
            source: autoMinorVersionUpgrade
            widget: Labels
          - name: spec.engineVersion
            source: engineVersion
            widget: Labels
          - name: spec.parameters
            source: parameters
            widget: Labels
          - name: spec.preferredMaintenanceWindow
            source: preferredMaintenanceWindow
            widget: Labels
          - name: spec.redisTier
            source: redisTier
            widget: Labels

      - name: spec.ipRange
        widget: Panel
        source: spec
        children:
          - name: spec.ipRange.name
            source: ipRange.name
            widget: Labels


      - name: spec.authEnabledFull
        widget: Panel
        source: spec
        children:
          - name: spec.authEnabled
            source: authEnabled
            widget: Labels

      - name: spec.authSecret
        widget: Panel
        source: spec
        children:
          - source: authSecret.name
            name: spec.authSecret.name
            widget: Labels
          - source: authSecret.labels
            name: spec.authSecret.labels
            widget: Labels
          - source: authSecret.annotations
            name: spec.authSecret.annotations
            widget: Labels
          - source: authSecret.extraData
            name: spec.authSecret.extraData
            widget: Labels
      - name: status
        widget: Panel
        source: status
        children:
          - name: status.state
            source: state
            widget: Labels
  form: |
    - path: spec.engineVersion
      name: spec.engineVersion
      required: false

    - path: spec.autoMinorVersionUpgrade
      name: spec.autoMinorVersionUpgrade
      widget: Switch
      required: false

    - path: spec.parameters
      name: spec.parameters
      required: false
      widget: KeyValuePair

    - path: spec
      name: spec.security
      widget: FormGroup
      children:
        - path: authEnabled
          name: spec.authEnabledFull
          widget: Switch
          required: false


    - path: spec.preferredMaintenanceWindow
      name: spec.preferredMaintenanceWindow
      required: false

    - path: spec.redisTier
      name: spec.redisTier
      required: true

    - path: spec.ipRange
      name: spec.ipRange
      widget: FormGroup
      required: false
      children:
        - path: name
          name: spec.ipRange.name
          widget: Text
          required: true

    - path: spec.authSecret
      name: spec.authSecret
      widget: FormGroup
      required: false
      children:
        - path: name
          name: spec.authSecret.name
          widget: Text
          required: true
        - path: labels
          name: spec.authSecret.labels
          required: false
          widget: KeyValuePair
        - path: annotations
          name: spec.authSecret.annotations
          required: false
          widget: KeyValuePair
        - path: extraData
          name: spec.authSecret.extraData
          required: false
          widget: KeyValuePair
  general: |
    resource:
        kind: AwsRedisInstance
        group: cloud-resources.kyma-project.io
        version: v1beta1
    urlPath: awsredisinstances
    name: AWS Redis Instance
    scope: namespace
    category: Storage
    icon: shelf
    description: >-
        AwsRedisInstance description here
  list: |-
    - source: status.state
      name: status.state
      sort: true
  translations: |
    en:
      configuration: Configuration
      status: Status
      status.state: State
      spec.ipRange: Ip Range
      spec.ipRange.name: Ip Range Name
      spec.auth: Authentication
      spec.authSecret: Authentication Secret
      spec.authEnabled: Enabled
      spec.authEnabledFull: Authentication Enabled
      spec.authSecret.name: Name
      spec.authSecret.labels: Labels
      spec.authSecret.annotations: Annotations
      spec.authSecret.extraData: Extra Data
      spec.autoMinorVersionUpgrade: Auto Minor Version Upgrade
      spec.engineVersion: Engine Version
      spec.parameters: Parameters
      spec.preferredMaintenanceWindow: Preferred Maintenance Window
      spec.redisTier: Redis Tier
kind: ConfigMap
metadata:
  annotations:
    cloud-resources.kyma-project.io/version: v0.0.9
  labels:
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    cloud-manager: ui-cm
  name: awsredisinstances-ui.operator.kyma-project.io
  namespace: kyma-system
