apiVersion: v1
data:
  details: |-
    body:
      - name: configuration
        widget: Panel
        source: spec
        children:
          - name: spec.capacity
            source: capacity
            widget: Labels
          - name: spec.performanceMode
            source: performanceMode
            widget: Labels
          - name: spec.volume.name
            source: volume.name
            widget: Labels
      - name: ipRange
        widget: Panel
        source: spec.ipRange
        children:
          - name: name
            source: name
            widget: Labels
          - name: namespace
            source: namespace
            widget: Labels
      - name: volume
        source: spec.volume
        widget: Panel
        children:
          - name: name
            source: name
            widget: Labels
          - name: labels
            source: labels
            widget: Labels
          - name: annotations
            source: annotations
            widget: Labels
      - name: status
        widget: Panel
        source: status
        children:
          - name: status.state
            source: state
            widget: Labels
  form: |
    - path: spec.capacity
      simple: true
      name: spec.capacity
      required: true
      widget: Text
    - path: spec.performanceMode
      simple: true
      name: spec.performanceMode
      required: true
      placeholder: placeholders.dropdown
    - path: spec.throughput
      simple: true
      name: spec.throughput
      required: true
      placeholder: placeholders.dropdown
    - path: spec.ipRange
      simple: true
      name: spec.ipRange
      widget: FormGroup
      children:
        - path: name
          name: name
          simple: true
          required: true
          widget: Text
        - path: namespace
          name: namespace
          simple: true
          required: true
          widget: Text
    - path: spec.volume
      simple: true
      name: spec.volume
      widget: FormGroup
      children:
        - path: name
          simple: true
          name: name
          required: true
          widget: Text
        - path: labels
          simple: true
          name: labels
          required: false
          widget: KeyValuePair
        - path: annotations
          simple: true
          name: annotations
          required: false
          widget: KeyValuePair
  general: |-
    resource:
        kind: AwsNfsVolume
        group: cloud-resources.kyma-project.io
        version: v1beta1
    urlPath: awsnfsvolumes
    name: AWS NFS Volumes
    scope: namespace
    category: Storage
    icon: shelf
    description: >-
        AWS NFS Volume description here
  list: |-
    - source: spec.capacity
      name: spec.capacity
      sort: true
    - source: spec.performanceMode
      name: spec.performanceMode
      sort: true
    - source: spec.throughput
      name: spec.throughput
      sort: true
    - source: spec.volume.name
      name: spec.volume.name
      sort: true
  translations: |-
    en:
      spec.capacity: Capacity
      spec.performanceMode: Performance Mode
      spec.throughput: Throughput
      spec.volume.name: Volume Name
      configuration: Configuration
      status: Status
      status.state: State
      placeholders.dropdown: Type or choose an option
      ipRange: IP Range
      name: Name
      namespace: Namespace
      spec.volume: Volume
      labels: Labels
      annotations: Annotations
      spec.ipRange: IP Range
kind: ConfigMap
metadata:
  labels:
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    cloud-manager: ui-cm
  name: awsnfsvolumes-ui.operator.kyma-project.io
  namespace: kyma-system
