configMapGenerator:
  - name: awsnfsvolumes-ui.operator.kyma-project.io
    files:
      - details
      - form
      - general
      - list
      - translations
    options:
        disableNameSuffixHash: true
        labels:
          cloud-manager: ui-cm
          busola.io/extension: resource
          busola.io/extension-version: "0.5"
        annotations:
          cloud-resources.kyma-project.io/version: "v0.0.2"
    namespace: kyma-system