apiVersion: v1
data:
  details: "body:\n  - name: spec.lifecycle\n    widget: Panel\n    source: spec.lifecycle\n
    \   children:\n      - name: spec.lifecycle.deleteAfterDays\n        source: deleteAfterDays\n
    \       widget: Labels\n      - name: spec.lifecycle.moveToColdStorageAfterDays\n
    \       source: moveToColdStorageAfterDays\n        widget: Labels\n  - name:
    configuration\n    widget: Panel\n    source: spec\n    children:\n      - name:
    spec.location\n        source: location\n        widget: Labels  \n      - name:
    spec.source.volume.name\n        source: name\n        widget: Labels\n      -
    name: spec.source.volume.namespace\n        source: namespace\n        widget:
    Labels\n  - name: status\n    widget: Panel\n    source: status\n    children:\n
    \     - widget: Labels\n        source: state\n        name: status.state\n      -
    widget: Labels\n        source: locations\n        name: status.locations\n      -
    widget: Labels\n        source: capacity\n        name: status.capacity\n"
  form: |
    - path: spec.lifecycle
      name: spec.lifecycle
      widget: FormGroup
      children:
        - path: deleteAfterDays
          name: spec.lifecycle.deleteAfterDays
          required: false
          widget: Number
        - path: moveToColdStorageAfterDays
          name: spec.lifecycle.moveToColdStorageAfterDays
          required: false
          widget: Number

    - path: spec.source.volume
      name: spec.source.volume
      widget: FormGroup
      children:
        - path: name
          name: spec.source.volume.name
          required: true
          widget: Text
        - path: namespace
          name: spec.source.volume.namespace
          required: false
          widget: Text

    - path: spec.location
      name: spec.location
      widget: FormGroup
      children:
        - path: spec.location
          name: spec.location
          required: false
          widget: Text
  general: |
    resource:
        kind: AwsNfsVolumeBackup
        group: cloud-resources.kyma-project.io
        version: v1beta1
    urlPath: awsnfsvolumebackups
    name: AWS NFS Volume Backups
    scope: namespace
    category: Storage
    icon: shelf
    description: >-
        AWS NFS Volume Backup description here
  list: |
    - source: status.locations
      name: status.locations
      sort: true
    - source: status.capacity
      name: status.capacity
      sort: true
    - source: spec.source.volume.name
      name: spec.source.volume.name
      sort: true
    - source: status.state
      name: status.state
      sort: true
  translations: |
    en:
      configuration: Configuration
      status: Status
      status.state: State
      status.locations: Allocated Locations
      status.capacity: Capacity
      spec.lifecycle: Lifecycle
      spec.lifecycle.deleteAfterDays: Delete After Days
      spec.lifecycle.moveToColdStorageAfterDays: Move to Cold Storage After Days
      spec.source.volume: Source Volume
      spec.source.volume.name: Name
      spec.source.volume.namespace: Namespace
      spec.location: Requested Location
kind: ConfigMap
metadata:
  annotations:
    cloud-resources.kyma-project.io/version: v0.0.4
  labels:
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    cloud-manager: ui-cm
  name: awsnfsvolumebackups-ui.operator.kyma-project.io
  namespace: kyma-system
