apiVersion: v1
data:
  details: |
    body:
        - name: configuration
          widget: Panel
          source: spec
          children:
            - name: spec.fileShareName
              source: fileShareName
              widget: Labels
            - name: spec.capacityGb
              source: capacityGb
              widget: Labels
            - name: spec.location
              source: location
              widget: Labels
            - name: spec.tier
              source: tier
              widget: Labels
        - name: spec.ipRange
          widget: Panel
          source: spec
          children:
            - name: spec.ipRange.name
              source: ipRange.name
              widget: Labels
        - name: spec.volume
          widget: Panel
          source: spec
          children:
            - source: volume.name
              name: spec.volume.name
              widget: Labels
            - source: volume.labels
              name: spec.volume.labels
              widget: Labels
            - source: volume.annotations
              name: spec.volume.annotations
              widget: Labels
        - name: spec.volumeClaim
          widget: Panel
          source: spec
          children:
            - source: volumeClaim.name
              name: spec.volumeClaim.name
              widget: Labels
            - source: volumeClaim.labels
              name: spec.volumeClaim.labels
              widget: Labels
            - source: volumeClaim.annotations
              name: spec.volumeClaim.annotations
              widget: Labels
        - name: spec.sourceBackup
          widget: Panel
          source: spec.sourceBackup
          children:
            - source: name
              name: spec.sourceBackup.name
              widget: Labels
            - source: namespace
              name: spec.sourceBackup.namespace
              widget: Labels
        - name: status
          widget: Panel
          source: status
          children:
            - widget: Labels
              source: state
              name: status.state
  form: |
    - path: spec.capacityGb
      name: spec.capacityGb
      required: true
    - path: spec.fileShareName
      name: spec.fileShareName
      required: true
      disableOnEdit: true
      description: Immutable once set.
    - path: spec.location
      name: spec.location
      required: true
      disableOnEdit: true
      description: Immutable once set.
    - path: spec.tier
      name: spec.tier
      required: true
      disableOnEdit: true
      description: Immutable once set.

    - path: spec.ipRange
      name: spec.ipRange
      widget: FormGroup
      required: false
      children:
        - path: name
          name: spec.ipRange.name
          widget: Text
          required: true
          disableOnEdit: true
          description: Immutable once set.
    - path: spec.volume
      name: spec.volume
      widget: FormGroup
      required: false
      children:
        - path: name
          name: spec.volume.name
          widget: Text
          required: true
        - path: labels
          name: spec.volume.labels
          required: false
          widget: KeyValuePair
        - path: annotations
          name: spec.volume.annotations
          required: false
          widget: KeyValuePair
    - path: spec.volumeClaim
      name: spec.volumeClaim
      widget: FormGroup
      required: false
      children:
        - path: name
          name: spec.volumeClaim.name
          widget: Text
          required: true
          disableOnEdit: true
          description: Immutable once set.
        - path: labels
          name: spec.volumeClaim.labels
          required: false
          widget: KeyValuePair
        - path: annotations
          name: spec.volumeClaim.annotations
          required: false
          widget: KeyValuePair
    - path: spec.sourceBackup
      name: spec.sourceBackup
      widget: FormGroup
      required: false
      children:
        - path: name
          name: spec.sourceBackup.name
          widget: Text
          required: true
          disableOnEdit: true
          description: Immutable once set.
        - path: namespace
          name: spec.sourceBackup.namespace
          widget: Text
          required: true
          disableOnEdit: true
          description: Immutable once set.
  general: |+
    resource:
        kind: GcpNfsVolume
        group: cloud-resources.kyma-project.io
        version: v1beta1
    urlPath: gcpnfsvolumes
    name: GCP NFS Volumes
    scope: namespace
    category: Storage
    icon: shelf
    description: >-
        GcpNfsVolume description here


  list: |
    - source: spec.fileShareName
      name: spec.fileShareName
      sort: true
    - source: spec.location
      name: spec.location
      sort: true
    - source: spec.tier
      name: spec.tier
      sort: true
    - source: status.state
      name: status.state
      sort: true
  translations: |
    en:
      spec.tier: Tier
      spec.location: Location
      spec.capacityGb: Capacity
      spec.fileShareName: File Share Name
      spec.capacityGb: Capacity (Gb)
      spec.ipRange: IP Range
      spec.ipRange.name: Name
      configuration: Configuration
      status.state: State
      status: Status
      spec.volume: Volume
      spec.volume.name: Name
      spec.volume.labels: Labels
      spec.volume.annotations: Annotations
      spec.volumeClaim: Volume Claim
      spec.volumeClaim.name: Name
      spec.volumeClaim.labels: Labels
      spec.volumeClaim.annotations: Annotations
      spec.sourceBackup: Source Backup
      spec.sourceBackup.name: Name
      spec.sourceBackup.namespace: Namespace
kind: ConfigMap
metadata:
  annotations:
    cloud-resources.kyma-project.io/version: v0.0.2
  labels:
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
    cloud-manager: ui-cm
  name: gcpnfsvolumes-ui.operator.kyma-project.io
  namespace: kyma-system
