name: Cloud-Manager Build

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-image-with-tag:
    if: github.ref_type == 'tag'
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      tags: ${{ github.ref_name }}
      name: cloud-manager
      dockerfile: Dockerfile
      export-tags: true
  build-image-no-tag:
    if: github.ref_type != 'tag'
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      tags: |
        ${{ github.ref_name }}
        latest
      name: cloud-manager
      dockerfile: Dockerfile
      export-tags: true
