name: Feature toggles

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  schema-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Go details
        run: |
          go env
      - name: Install jv
        run: |
          go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
      - name: Validate schema
        run: |
          GO_FEATURE_FLAG_VERSION=$(grep "github.com/thomaspoignant/go-feature-flag " ./go.mod | awk '{print $2}')
          SCHEMA_URL="https://raw.githubusercontent.com/thomaspoignant/go-feature-flag/$GO_FEATURE_FLAG_VERSION/.schema/flag-schema.json"
          jv --assert-content --assert-format $SCHEMA_URL ./pkg/feature/default.yaml

